baseURL = 'https://luuvish.github.io/article/'
languageCode = 'ko-kr'
title = 'Luuvish Article'
defaultContentLanguage = 'ko'
enableRobotsTXT = true

[pagination]
pagerSize = 10

[params]
description = 'luuvish의 연구/개발 기록'
author = 'Luuvish'

[[menus.main]]
name = '홈'
url = '/'
weight = 1

[[menus.main]]
name = '글'
url = '/posts/'
weight = 2
